# Generated by Django 4.1.5 on 2023-02-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_cd', models.IntegerField()),
                ('rr_cd', models.IntegerField()),
                ('company_name', models.CharField(max_length=80)),
                ('company_name_k', models.CharField(blank=True, max_length=80, null=True)),
                ('company_name_h', models.CharField(blank=True, max_length=80, null=True)),
                ('company_name_r', models.CharField(blank=True, max_length=80, null=True)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('company_type', models.IntegerField(blank=True, null=True)),
                ('e_status', models.IntegerField()),
                ('e_sort', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Line',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_cd', models.IntegerField()),
                ('company_cd', models.IntegerField()),
                ('line_name', models.CharField(max_length=80)),
                ('line_name_k', models.CharField(blank=True, max_length=80, null=True)),
                ('line_name_h', models.CharField(blank=True, max_length=80, null=True)),
                ('line_color_c', models.CharField(blank=True, max_length=80, null=True)),
                ('line_color_t', models.CharField(blank=True, max_length=80, null=True)),
                ('line_type', models.IntegerField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('zoom', models.IntegerField()),
                ('e_status', models.IntegerField()),
                ('e_sort', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Line',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_cd', models.IntegerField()),
                ('station_g_cd', models.IntegerField()),
                ('station_name', models.CharField(max_length=80)),
                ('station_name_k', models.CharField(blank=True, max_length=80, null=True)),
                ('station_name_r', models.CharField(blank=True, max_length=200, null=True)),
                ('pref_cd', models.IntegerField(blank=True, null=True)),
                ('post', models.CharField(blank=True, max_length=10, null=True)),
                ('add', models.CharField(blank=True, max_length=300, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('open_ymd', models.DateField(blank=True, null=True)),
                ('close_ymd', models.DateField(blank=True, null=True)),
                ('e_status', models.IntegerField(blank=True, null=True)),
                ('e_sort', models.IntegerField(blank=True, null=True)),
                ('line_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_data.line')),
            ],
            options={
                'verbose_name': 'Station',
            },
        ),
        migrations.CreateModel(
            name='ConnectedStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_data.line')),
                ('station_cd1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_cd1', to='station_data.station')),
                ('station_cd2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_cd2', to='station_data.station')),
            ],
            options={
                'verbose_name': 'ConnectedStation',
            },
        ),
    ]
