# Generated by Django 4.1.5 on 2023-02-27 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company'},
        ),
    ]
