# Generated by Django 4.1.5 on 2023-02-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_data', '0002_alter_company_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedstation',
            name='station_cd1',
        ),
        migrations.RemoveField(
            model_name='connectedstation',
            name='station_cd2',
        ),
        migrations.AddField(
            model_name='connectedstation',
            name='station_cd1',
            field=models.ManyToManyField(related_name='station_cd1', to='station_data.station'),
        ),
        migrations.AddField(
            model_name='connectedstation',
            name='station_cd2',
            field=models.ManyToManyField(related_name='station_cd2', to='station_data.station'),
        ),
    ]
