# Generated by Django 4.1.5 on 2023-03-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_data', '0003_remove_connectedstation_station_cd1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='company_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_data.company'),
        ),
    ]
